### ISSUE TITLE
Create spider to Sakura Cards

### ISSUE THREAD

**Issue by alvesmatheus** [alvesmatheus/Sakura#1]
The `sakura_cards_spider.py` (very similar to `clow_cards_spider.py`) will crawl the [FANDOM Wiki ](https://ccsakura.fandom.com/wiki/Cardcaptor_Sakura_Wiki) to get information about the Sakura Cards.

At this point, the only differences between the data that will be gathered are: 
- The URL for the cards images.
- *The Hope* and *The Nameless Card* have Sakura Card forms.

It's necessary to create new **Item**, **Loader** and **selectors** to this spider.

**Comment by rpartha** [comment]
dibs!

**Comment by alvesmatheus** [comment]
Closed by #2
